### ISSUE TITLE
Multiple configs are possible, but there's only one hardcoded 

### ISSUE THREAD

**Issue by pstadler1990** [pstadler1990/che#16]
... in `configuration.py`

Maybe we need to add a switch to the CLI, or use a new, different file containing the configuration of multiple sites.

```
site_a:
  config: config.yml
site_b:
  config: config_2.yml
```
